[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dreem"
authors = [{name = "Yves Martin des Taillades", email = "yves@martin.yt"}]
dynamic = ["version", "description"]
